### ISSUE TITLE
Nodejs not installing 4.x version

### ISSUE THREAD

**Issue by joeldevnull** [phpdocker/phpdocker#1]
Having some problems with Nodejs not being a high enough version (>0.12), but noticed the Dockerfile should be installing Nodejs 4.x LTS from nodesource anyway? It seems like its failing and falling back to the default Debian repository version?

The output from Docker is:

`+ npm --version
1.4.21
- node --version
  v0.10.29`

**Comment by hranicka** [comment]
@joelyuk Hi, thanks for report. Soon I'll look into it.

**Comment by hranicka** [comment]
Closed via 4f33cb2

Just wait for rebuilds on [Docker Hub](https://hub.docker.com/r/phpdocker/phpdocker/tags/).
